version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: idealistia-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-idealistia}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: idealistia-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_NAME: ${DB_NAME:-idealistia}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: idealistia-frontend
    depends_on:
      - backend
    environment: {}
    ports:
      - "8080:80"

volumes:
  db_data:
